import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import styles from "@/styles/Home.module.css";
import Card from "@/components/Card";
import { v4 as uuidv4 } from "uuid";

const mockCardDetails = [
  { name: "card1", value: "value1" },
  { name: "card2", value: "value2" },
];

export default function Home() {
  const [cardDetails, setCardDetails] = useState([{}]);

  useEffect(() => {
    setCardDetails(mockCardDetails);
  }, []);

  const handleClick = (newDetails) => {
    setCardDetails([...cardDetails, newDetails]);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {cardDetails.map((card) => (
          <Card handleClick={handleClick} key={uuidv4()}>
            {card.value}
          </Card>
        ))}
      </main>
    </>
  );
}
